env:
  browser: true
  jquery: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  indent:
    - error
    - 2
    - "SwitchCase": 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-undef-init: error
  no-undefined: "off"
  no-undef: "off"
  no-unused-vars: "off"